# Generated by Django 5.0.1 on 2024-02-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="post",
            old_name="pet_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="pet_breed",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="pet_genre",
        ),
        migrations.RemoveField(
            model_name="post",
            name="pet_images",
        ),
        migrations.RemoveField(
            model_name="post",
            name="pet_name",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.AddField(
            model_name="post",
            name="reward",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=280)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "female"), ("Male", "male")], max_length=6
                    ),
                ),
                ("breed", models.CharField(max_length=30)),
                ("status", models.CharField(default="Lost", max_length=6)),
                (
                    "last_local",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pets",
                        to="posts.local",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="", upload_to="posts/")),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.pet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="pet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.pet",
            ),
            preserve_default=False,
        ),
    ]
