# Generated by Django 5.0.1 on 2024-02-06 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_local_rename_pet_description_post_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="image",
            field=models.ImageField(
                default="", upload_to="posts/", verbose_name="Imagem"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="local",
            name="neighborhood",
            field=models.CharField(max_length=100, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="local",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Rua"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(max_length=30, verbose_name="Raça"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="description",
            field=models.CharField(max_length=280, verbose_name="Descrição do Pet"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "female"),
                    ("Male", "male"),
                    ("Unknown", "unknown"),
                ],
                max_length=7,
                verbose_name="Gênero",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="last_local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pets",
                to="posts.local",
                verbose_name="Última localização",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nome do Pet"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tutor",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[("Lost", "lost"), ("Found", "found")],
                max_length=6,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=280, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="post",
            name="reward",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Recompensa",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Titulo"),
        ),
        migrations.DeleteModel(
            name="Images",
        ),
    ]
