# Generated by Django 5.0.1 on 2024-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_pet_image_post_slug_alter_local_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(max_length=50, verbose_name="Raça"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Titulo"),
        ),
    ]
