# Generated by Django 5.0.1 on 2024-02-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_pet_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="local",
            name="neighborhood",
            field=models.CharField(max_length=100, verbose_name="Neighborhood"),
        ),
        migrations.AlterField(
            model_name="local",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(max_length=50, verbose_name="Breed"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="description",
            field=models.CharField(max_length=280, verbose_name="Pet Description"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "female"),
                    ("Male", "male"),
                    ("Unknown", "unknown"),
                ],
                max_length=7,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=models.ImageField(
                default="", upload_to="posts/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="last_local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pets",
                to="posts.local",
                verbose_name="Last Location",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=10, verbose_name="Pet Name"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[("Lost", "lost"), ("Found", "found")],
                max_length=6,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[("Dog", "dog"), ("Cat", "cat"), ("Bird", "bird")],
                max_length=5,
                verbose_name="Pet Type",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=280, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="post",
            name="reward",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Reward",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Title"),
        ),
    ]
