# Generated by Django 5.0.1 on 2024-02-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_alter_local_city_alter_local_neighborhood_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="", upload_to="posts/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
    ]
