# Generated by Django 5.0.1 on 2024-02-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="", upload_to="postsImages/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
    ]
