# Generated by Django 5.0.1 on 2024-02-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_alter_pet_owner_alter_post_image_alter_post_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[
                    ("Dog", "dog"),
                    ("Cat", "cat"),
                    ("Bird", "bird"),
                    ("Others", "others"),
                ],
                max_length=6,
                verbose_name="Pet Type",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="", upload_to="posts-images/", verbose_name="Image"
            ),
        ),
    ]
