# Generated by Django 5.0.1 on 2024-02-16 01:52

import posts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_alter_pet_type_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=posts.models.ImageField(
                default="", upload_to="posts-images/", verbose_name="Image"
            ),
        ),
    ]
