# Generated by Django 5.0.1 on 2024-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.CharField(default="sWF8da", max_length=6),
        ),
    ]
