# Generated by Django 5.0.1 on 2024-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.CharField(default="lBOQzY", max_length=6),
        ),
    ]
