# Generated by Django 5.0.1 on 2024-02-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="code",
        ),
    ]
