# Generated by Django 5.0.1 on 2024-02-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_code",
            field=models.CharField(default="", max_length=6),
        ),
    ]
