# Generated by Django 5.0.1 on 2024-02-06 23:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="A short label for URLs",
            ),
        ),
    ]
