# Generated by Django 5.0.1 on 2024-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user__code_alter_user_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="User", max_length=100),
        ),
    ]
