# Generated by Django 5.0.1 on 2024-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_bio_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_validated",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
