# Generated by Django 5.0.1 on 2024-02-09 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_user_email_validated_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("4c314843-9f79-4a65-b537-c4086cd3a351"),
                editable=False,
            ),
        ),
    ]
