# Generated by Django 5.0.1 on 2024-02-09 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("3f8b1cb6-ad07-4204-8006-3b227b70ccfd"),
                editable=False,
            ),
        ),
    ]
