# Generated by Django 5.0.1 on 2024-02-09 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("4cda07b9-696d-4571-8924-782a5aee9453"),
                editable=False,
            ),
        ),
    ]
