# Generated by Django 5.0.1 on 2024-02-09 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("e06271b7-b862-49bc-8b9e-f0a1b9a1a189"),
                editable=False,
            ),
        ),
    ]
