# Generated by Django 5.0.1 on 2024-02-09 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("9075f6a9-e10d-41cb-abe7-ae9fd6b81fb3"),
                editable=False,
            ),
        ),
    ]
