# Generated by Django 5.0.1 on 2024-02-09 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("f8386127-626d-4d34-9d04-2c2f6b5ccbd8"),
                editable=False,
            ),
        ),
    ]
