# Generated by Django 5.0.1 on 2024-02-14 21:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_user_role_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("7217a05c-c192-4d0d-a8d8-6e24a8aff6fc"),
                editable=False,
            ),
        ),
    ]
