# Generated by Django 5.0.1 on 2024-02-14 22:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(
                default=uuid.UUID("c7a8fb23-673a-47ba-aa8c-4675b2b3e5a3"),
                editable=False,
            ),
        ),
    ]
