# Generated by Django 5.0.1 on 2024-02-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_user__code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_code",
            field=models.UUIDField(editable=False),
        ),
    ]
